name: fineartimage
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2890994646586478
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d3e5e6'
    - '#2b231b'
    - '#595042'
    - '#9b9588'
  brandStrength: 0.4078983801882714
  lightness: 0.47955919592641294
  saturation: 0.45681849936954677
  rhythmicContrast: 0.5537553660105914
purpose: []
