name: fineartimage
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2890994646586478
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#cbd5de'
    - '#afaba0'
    - '#163003'
    - '#a07d3f'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
